#!/usr/bin/env node
/**
 * Screenshot pipeline for the Velxio docs.
 *
 *   VELXIO_SHOTS_EMAIL=... VELXIO_SHOTS_PASSWORD=... node scripts/shots.mjs [scene ...]
 *
 * Captures every documented scene against a running Velxio instance
 * (default: the staging deployment) and writes them to src/assets/docs/.
 * Screenshots are regenerated by re-running this script — never edit or
 * paste them by hand, they must stay reproducible when the UI changes.
 *
 * With scene names as args, only those scenes run. `--list` prints them.
 * `--inventory` additionally dumps every visible button/label to
 * scripts/ui-inventory.json (used to maintain the selectors below).
 *
 * Env:
 *   VELXIO_BASE            target instance (default https://vstaging.moontero.com)
 *   VELXIO_SHOTS_EMAIL     login email  (required — use a test account, the
 *   VELXIO_SHOTS_PASSWORD  login pass    account name shows in the top bar)
 */
import { globSync, mkdirSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { chromium } from "playwright";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, "..", "src", "assets", "docs");
const BASE = process.env.VELXIO_BASE || "https://vstaging.moontero.com";
const EMAIL = process.env.VELXIO_SHOTS_EMAIL;
const PASS = process.env.VELXIO_SHOTS_PASSWORD;

const VIEWPORT = { width: 1280, height: 720 };

// ── infra ────────────────────────────────────────────────────────────────────

async function launch() {
  try {
    return await chromium.launch({ headless: true });
  } catch {
    const home = process.env.HOME;
    const candidates = [
      ...globSync(
        `${home}/.cache/ms-playwright/chromium_headless_shell-*/chrome-headless-shell-linux64/chrome-headless-shell`
      ),
      ...globSync(
        `${home}/.cache/ms-playwright/chromium-*/chrome-linux*/chrome`
      ),
    ]
      .sort()
      .reverse();
    if (!candidates.length)
      throw new Error("no chromium — run: npx playwright install chromium");
    return chromium.launch({ headless: true, executablePath: candidates[0] });
  }
}

/** Form login is flaky on staging; the JSON endpoint is not. Log in via
 *  fetch inside the page so the session cookie lands in the browser jar. */
async function login(page) {
  if (!EMAIL || !PASS)
    throw new Error("VELXIO_SHOTS_EMAIL / VELXIO_SHOTS_PASSWORD not set");
  await page.goto(`${BASE}/`, { waitUntil: "domcontentloaded" });
  const status = await page.evaluate(
    async ({ email, password }) => {
      const r = await fetch("/api/auth/login", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ email, password }),
        credentials: "include",
      });
      return r.status;
    },
    { email: EMAIL, password: PASS }
  );
  if (status !== 200) throw new Error(`login failed: HTTP ${status}`);
  await page.reload({ waitUntil: "domcontentloaded" });
  await page.waitForTimeout(3000);
}

/** The news/announcement overlay opens over the toolbar on fresh sessions
 *  and swallows clicks; the GitHub star banner drifts in a few seconds later
 *  and covers the bottom-right corner (the serial monitor). Both are
 *  presentational — safe to remove. The star banner is on a timer, so call
 *  this again before any shot taken well after the page settles. */
async function dismissOverlays(page) {
  await page.evaluate(() => {
    for (const el of document.querySelectorAll(
      ".velxio-news-overlay, .gh-star-banner"
    ))
      el.remove();
  });
}

async function shot(page, relPath, opts = {}) {
  const file = join(OUT, `${relPath}.png`);
  mkdirSync(dirname(file), { recursive: true });
  await page.screenshot({ path: file, fullPage: false, ...opts });
  console.log(`  saved ${relPath}.png`);
}

/** Dump every visible interactive element so scene selectors can be
 *  maintained without spelunking the frontend source. */
async function inventory(page, name) {
  const items = await page.evaluate(() => {
    const out = [];
    const walk = root => {
      for (const el of root.querySelectorAll(
        "button, a[href], [role=button], input, select"
      )) {
        const r = el.getBoundingClientRect();
        if (r.width < 2 || r.height < 2) continue;
        out.push({
          tag: el.tagName.toLowerCase(),
          text: (el.textContent || "").trim().slice(0, 60),
          title: el.getAttribute("title") || undefined,
          aria: el.getAttribute("aria-label") || undefined,
          cls: (el.className?.baseVal ?? el.className ?? "")
            .toString()
            .slice(0, 80),
          at: [
            Math.round(r.x),
            Math.round(r.y),
            Math.round(r.width),
            Math.round(r.height),
          ],
        });
      }
      for (const el of root.querySelectorAll("*"))
        if (el.shadowRoot) walk(el.shadowRoot);
    };
    walk(document);
    return out;
  });
  const file = join(HERE, `ui-inventory-${name}.json`);
  await writeFile(file, JSON.stringify(items, null, 2));
  console.log(`  inventory -> ${file} (${items.length} elements)`);
}

async function waitForSim(page, simLog, ms = 300_000) {
  const t0 = Date.now();
  while (Date.now() - t0 < ms) {
    if (simLog.some(l => l.includes("in-browser"))) return true;
    if (simLog.some(l => /guest crashed/i.test(l))) return false;
    await page.waitForTimeout(2000);
  }
  return false;
}

/** The AI panel takes a third of the width; screenshots that are not
 *  about the assistant read much better without it. */
async function minimizeAi(page) {
  const b = page.locator(
    'button[aria-label="Minimize chat"], button[title="Minimize"]'
  );
  if (await b.count()) {
    await b.first().click();
    await page.waitForTimeout(600);
  }
}

async function loadExample(page, slug, { keepAi = false } = {}) {
  await page.goto(`${BASE}/example/${slug}`, { waitUntil: "domcontentloaded" });
  await page.waitForTimeout(6000); // canvas + example hydration
  await dismissOverlays(page);
  if (!keepAi) await minimizeAi(page);
}

async function clickRun(page) {
  await page
    .locator('button[title*="Run" i], button:has-text("Run")')
    .first()
    .click();
}

/** Clip rectangle covering every given selector, padded.
 *
 *  Hardcoded pixel clips silently rot: when the toolbar moved, the
 *  transport shot kept "succeeding" while capturing two lines of the code
 *  editor. Measuring the real elements means a moved control produces a
 *  correct shot, and a REMOVED control throws instead of shipping a lie. */
async function clipOf(page, selectors, pad = 10) {
  let x0 = Infinity,
    y0 = Infinity,
    x1 = -Infinity,
    y1 = -Infinity;
  for (const sel of selectors) {
    const box = await page.locator(sel).first().boundingBox();
    if (!box) throw new Error(`clipOf: nothing matched ${sel}`);
    x0 = Math.min(x0, box.x);
    y0 = Math.min(y0, box.y);
    x1 = Math.max(x1, box.x + box.width);
    y1 = Math.max(y1, box.y + box.height);
  }
  const x = Math.max(0, Math.round(x0 - pad));
  const y = Math.max(0, Math.round(y0 - pad));
  return {
    x,
    y,
    width: Math.min(VIEWPORT.width - x, Math.round(x1 - x0 + pad * 2)),
    height: Math.min(VIEWPORT.height - y, Math.round(y1 - y0 + pad * 2)),
  };
}

/** The Library Manager fetches the installed set after it opens; shooting
 *  on a fixed timeout captured "Loading installed libraries..." in an empty
 *  panel. Wait for the list to actually render before the shutter. */
async function waitForLibraryList(page, ms = 30_000) {
  await page
    .locator("text=/Loading installed libraries/i")
    .waitFor({ state: "hidden", timeout: ms })
    .catch(() => {});
  await page
    .locator('.lib-list button:has-text("Add to project")')
    .first()
    .waitFor({ state: "visible", timeout: ms });
  await page.waitForTimeout(800); // let rows settle / images decode
}

// ── scenes ───────────────────────────────────────────────────────────────────
// Each scene navigates, prepares the state and captures one or more shots.
// Keep scenes independent: assume a fresh logged-in page, no leftover state.

const SCENES = {
  /** The editor as a signed-in user first sees it. */
  "getting-started/app-home": async page => {
    await page.goto(`${BASE}/`, { waitUntil: "domcontentloaded" });
    await page.waitForTimeout(6000);
    await dismissOverlays(page);
    await minimizeAi(page);
    await shot(page, "getting-started/app-home");
    if (WANT_INVENTORY) await inventory(page, "app-home");
  },

  /** One close-up per region described in the interface-tour page. Every
   *  clip is measured from the live element, so a UI reshuffle moves the
   *  crop instead of silently capturing the wrong pixels. */
  "getting-started/interface-tour": async page => {
    await loadExample(page, "esp32-blink-led", { keepAi: true });
    // The menu bar is whatever sits above the toolbar row.
    const bar = await page.locator(".header-editor-toolbar").first().boundingBox();
    if (!bar) throw new Error("toolbar not found");
    await shot(page, "getting-started/interface-menu-bar", {
      clip: { x: 0, y: 0, width: Math.round(bar.width), height: Math.round(bar.y) },
    });
    await shot(page, "getting-started/interface-toolbar", {
      clip: await clipOf(page, [".header-editor-toolbar"], 0),
    });
    await shot(page, "getting-started/interface-workspace", {
      clip: await clipOf(page, [".file-explorer"], 0),
    });
    // The blink circuit is wider than the canvas pane at 1:1, so the LED
    // and its resistor fall outside the crop. One zoom-out step fits the
    // whole circuit; "Reset view" would not — it jumps to the canvas
    // origin rather than centring on what is placed.
    const zoomOut = page.locator('button[title="Zoom out"]');
    if (await zoomOut.count()) {
      await zoomOut.first().click();
      await page.waitForTimeout(700);
    }
    await shot(page, "getting-started/interface-canvas", {
      clip: await clipOf(page, [".simulator-panel"], 0),
    });
    await shot(page, "getting-started/interface-ai-panel", {
      clip: await clipOf(page, [".velxio-agent-panel"], 0),
    });
  },

  /** Blink example: loaded, then running with the sim alive. */
  "getting-started/first-project": async page => {
    const simLog = [];
    page.on("console", m => {
      if (/esp32sim|guest crashed|in-browser/i.test(m.text()))
        simLog.push(m.text());
    });
    await loadExample(page, "esp32-blink-led");
    await shot(page, "getting-started/first-project-loaded");
    if (WANT_INVENTORY) await inventory(page, "example-editor");
    await clickRun(page);
    await waitForSim(page, simLog);
    await page.waitForTimeout(5000); // guest boot + first blinks
    await shot(page, "getting-started/first-project-running");
  },

  /** The public examples gallery. */
  "getting-started/examples-gallery": async page => {
    await page.goto(`${BASE}/examples`, { waitUntil: "domcontentloaded" });
    await page.waitForTimeout(4000);
    await dismissOverlays(page);
    await shot(page, "getting-started/examples-gallery");
    if (WANT_INVENTORY) await inventory(page, "examples-gallery");
  },

  /** Editor dialogs that need no running sim: component picker, datasheet
   *  (right-click), part properties, save-project, starter templates. */
  "circuit-editor/dialogs": async page => {
    await loadExample(page, "esp32-blink-led");

    // Component picker ("Add" in the toolbar)
    await page.locator('button[title="Add Component"]').click();
    await page.waitForTimeout(1500);
    await shot(page, "circuit-editor/component-picker");
    if (WANT_INVENTORY) await inventory(page, "component-picker");
    await page.keyboard.press("Escape");
    await page.waitForTimeout(500);

    // Part inspector (right-click a part: properties, pins and datasheet).
    // Playwright's right-click gets swallowed somewhere in the canvas stack,
    // so dispatch the contextmenu event directly — React listens at the root.
    await page.evaluate(() => {
      // The LED, not the resistor: the LED has an authored datasheet, so the
      // Datasheet tab shot shows real content instead of the empty state.
      const el = document.querySelector("wokwi-led");
      const r = el.getBoundingClientRect();
      el.dispatchEvent(
        new MouseEvent("contextmenu", {
          bubbles: true,
          cancelable: true,
          clientX: Math.min(r.x + r.width / 2, 640),
          clientY: Math.min(r.y + r.height / 2, 400),
        })
      );
    });
    await page.waitForTimeout(1500);
    await shot(page, "circuit-editor/part-inspector");
    if (WANT_INVENTORY) await inventory(page, "part-inspector");
    await page.locator('text="Datasheet"').first().click();
    await page.waitForTimeout(1000);
    await shot(page, "circuit-editor/datasheet");
    await page.keyboard.press("Escape");
    await page.waitForTimeout(500);

    // Save project dialog
    await page.locator('button[title^="Save project"]').click();
    await page.waitForTimeout(1200);
    await shot(page, "getting-started/save-project");
    await page.locator('button:has-text("Cancel")').first().click();
    await page.waitForTimeout(500);

    // Starter template picker (modal, per David's preference)
    await page.locator('button[title^="New workspace"]').click();
    await page.waitForTimeout(1200);
    await shot(page, "getting-started/starter-templates");
    if (WANT_INVENTORY) await inventory(page, "starter-templates");
    await page.keyboard.press("Escape");
  },

  /** Oscilloscope over the running blink example. */
  "instruments/oscilloscope": async page => {
    const simLog = [];
    page.on("console", m => {
      if (/esp32sim|guest crashed|in-browser/i.test(m.text()))
        simLog.push(m.text());
    });
    await loadExample(page, "esp32-blink-led");
    await clickRun(page);
    await waitForSim(page, simLog);
    await page.waitForTimeout(4000);
    await page
      .locator('button[title="Toggle Oscilloscope / Logic Analyzer"]')
      .click();
    await page.waitForTimeout(1500);
    // Monitor the blinking pin: add a channel on GPIO2
    await page.locator('button:has-text("Add Channel")').click();
    await page.waitForTimeout(1200);
    await shot(page, "instruments/oscilloscope-add-channel");
    if (WANT_INVENTORY) await inventory(page, "oscilloscope-pinpicker");
    await page.locator('button:text-is("GPIO2")').click();
    // 100 ms/div frames the 1 s blink square wave nicely (1 ms/div is flat)
    await page.locator("select.osc-select").first().selectOption("100");
    await page.waitForTimeout(6000); // let traces accumulate
    await shot(page, "instruments/oscilloscope");
    if (WANT_INVENTORY) await inventory(page, "oscilloscope");
  },

  /** Serial monitor close-up over the running blink example. */
  "programming/serial-monitor": async page => {
    const simLog = [];
    page.on("console", m => {
      if (/esp32sim|guest crashed|in-browser/i.test(m.text()))
        simLog.push(m.text());
    });
    await loadExample(page, "esp32-blink-led");
    await clickRun(page);
    await waitForSim(page, simLog);
    await page.waitForTimeout(6000); // some serial output first
    await shot(page, "programming/serial-monitor", {
      clip: { x: 0, y: 510, width: 1280, height: 210 },
    });
  },

  /** Libraries modal + transport buttons clip + full editor after a build. */
  "programming/details": async page => {
    const simLog = [];
    page.on("console", m => {
      if (/esp32sim|guest crashed|in-browser/i.test(m.text()))
        simLog.push(m.text());
    });
    await loadExample(page, "esp32-blink-led");
    await page.locator('button:has-text("Libraries")').click();
    await waitForLibraryList(page);
    await shot(page, "programming/libraries", {
      clip: await clipOf(page, [".lib-modal"], 12),
    });
    await page.keyboard.press("Escape");
    await page.waitForTimeout(500);
    // Language selector + compile/run/stop/reset cluster
    await shot(page, "programming/transport", {
      clip: await clipOf(page, [
        "select",
        'button[title*="Compile" i]',
        'button[title*="Reset" i]',
      ]),
    });
    await clickRun(page);
    await waitForSim(page, simLog);
    await page.waitForTimeout(4000);
    await shot(page, "programming/compile-and-run");
    // SPICE badge close-up for the analog page. The badge is an SVG <text>
    // inside a <g> that draws the chip, and it rides above the board — so
    // its position moves with the canvas view. Anchor the crop on the
    // parent <g> (the chip itself), never on fixed pixels.
    const badge = page.locator("text=/nets \\|/i").first().locator("xpath=..");
    const bb = await badge.boundingBox();
    if (!bb) throw new Error("SPICE badge not found");
    await shot(page, "instruments/spice-badge", {
      clip: {
        x: Math.max(0, Math.round(bb.x - 10)),
        y: Math.max(0, Math.round(bb.y - 10)),
        width: Math.round(bb.width + 20),
        height: Math.round(bb.height + 20),
      },
    });
  },

  /** WiFi+MQTT example running — serial shows join, DHCP and broker I/O. */
  "wifi-iot/mqtt": async page => {
    const simLog = [];
    page.on("console", m => {
      if (/esp32sim|guest crashed|in-browser/i.test(m.text()))
        simLog.push(m.text());
    });
    await loadExample(page, "esp32-wifi-mqtt");
    await clickRun(page);
    await waitForSim(page, simLog);
    await page.waitForTimeout(30000); // join + DHCP + broker connect
    await shot(page, "wifi-iot/mqtt-running");
    await shot(page, "wifi-iot/serial-wifi", {
      clip: { x: 410, y: 300, width: 870, height: 220 },
    });
  },

  /** Custom chip on the canvas and its editor dialog. */
  "custom-chips/dialog": async page => {
    await loadExample(page, "esp32-blink-led");
    await page.locator('button[title="Add Component"]').click();
    await page.waitForTimeout(1200);
    await page.locator('input[placeholder*="Search" i]').fill("custom chip");
    await page.waitForTimeout(800);
    await page.locator(".component-card, [class*=card]").first().click();
    await page.waitForTimeout(1500);
    // the chip lands on the canvas — open its editor via right-click
    await page.evaluate(() => {
      const el = [...document.querySelectorAll("*")].find(e =>
        e.tagName?.toLowerCase().includes("custom-chip")
      );
      const r = el.getBoundingClientRect();
      el.dispatchEvent(
        new MouseEvent("contextmenu", {
          bubbles: true,
          cancelable: true,
          clientX: Math.min(r.x + r.width / 2, 640),
          clientY: Math.min(r.y + r.height / 2, 380),
        })
      );
    });
    await page.waitForTimeout(1200);
    if (WANT_INVENTORY) await inventory(page, "custom-chip-inspector");
    const edit = page.locator(
      'button:has-text("Edit Chip"), button:has-text("Edit chip"), button:has-text("Edit")'
    );
    if (await edit.count()) {
      await edit.first().click();
      await page.waitForTimeout(1500);
    }
    await shot(page, "custom-chips/chip-editor");
  },

  /** Board context menu -> Flash to real board dialog. The Flash action
   *  is disabled until a binary exists, so compile first. */
  "wifi-iot/flash": async page => {
    await loadExample(page, "esp32-blink-led");
    await page.locator('button[title^="Compile"]').click();
    // cached builds return fast; poll the button's enablement below anyway
    await page.waitForTimeout(45000);
    await page.evaluate(() => {
      const el = document.querySelector("velxio-esp32");
      const r = el.getBoundingClientRect();
      el.dispatchEvent(
        new MouseEvent("contextmenu", {
          bubbles: true,
          cancelable: true,
          clientX: r.x + r.width / 2,
          clientY: r.y + 30,
        })
      );
    });
    await page.waitForTimeout(1200);
    if (WANT_INVENTORY) await inventory(page, "board-context");
    await page
      .locator('text=/Flash.*(real|board)/i')
      .first()
      .click();
    await page.waitForTimeout(2000);
    await shot(page, "wifi-iot/flash-modal");
  },

  /** MicroPython: the night-light example (LDR + LED) in editor and running. */
  "programming/micropython": async page => {
    const simLog = [];
    page.on("console", m => {
      if (/esp32sim|guest crashed|in-browser/i.test(m.text()))
        simLog.push(m.text());
    });
    await loadExample(
      page,
      "100d-auto-night-light-using-ldr-esp32-plus-micropython"
    );
    await shot(page, "programming/micropython-editor");
    await clickRun(page);
    await waitForSim(page, simLog);
    await page.waitForTimeout(8000);
    await shot(page, "programming/micropython-running");
  },

  /** The AI panel in each of its three modes (right-hand column clip). */
  "ai/modes": async page => {
    await loadExample(page, "esp32-blink-led", { keepAi: true });
    const clip = { x: 900, y: 0, width: 380, height: 720 };
    for (const mode of ["Basic", "Agent", "Tutor"]) {
      await page.locator(`button.mode-pill:has-text("${mode}")`).click();
      await page.waitForTimeout(1200);
      await shot(page, `ai/mode-${mode.toLowerCase()}`, { clip });
    }
  },

  /** M5 Cardputer ADV walkthrough for its board reference page: the gallery
   *  filtered to the board, the hello example loaded, running, and echoing
   *  typed keys. Consumed by scripts/board-extras/cardputer-adv.md. */
  "boards/cardputer-adv": async page => {
    // Gallery, filtered through the search box the docs tell readers to use.
    await page.goto(`${BASE}/examples`, { waitUntil: "domcontentloaded" });
    await page.waitForTimeout(4000);
    await dismissOverlays(page);
    await page.locator("input.examples-search-input").fill("cardputer");
    await page.waitForTimeout(1500);
    await shot(page, "boards/cardputer-adv-gallery");

    const simLog = [];
    page.on("console", m => {
      if (/esp32sim|guest crashed|in-browser/i.test(m.text()))
        simLog.push(m.text());
    });
    await loadExample(page, "cardputer-adv-hello");
    await shot(page, "boards/cardputer-adv-editor");

    await clickRun(page);
    await waitForSim(page, simLog);
    await page.waitForTimeout(12000); // guest boot + title screen draw
    await dismissOverlays(page); // star banner lands over the serial monitor
    await shot(page, "boards/cardputer-adv-running");

    // Focus the board so it owns the keyboard, then type — the emulated
    // TCA8418 turns real keystrokes into matrix presses.
    await page.locator("velxio-cardputer-adv").click();
    await page.waitForTimeout(800);
    await page.keyboard.type("hello velxio", { delay: 200 });
    await page.waitForTimeout(1500);
    await dismissOverlays(page);

    // Close-up: at 100% the 240x135 LCD is downscaled to ~100x60 and the
    // echoed text — the whole point of this shot — turns to mush. Zoom in
    // while the board still fits; each click is 1.1x anchored at the pane
    // corner, so the board drifts and a fixed step count would push it
    // half-off. Measure after every step and back off once it overflows.
    //
    // Measure against .canvas-content, the overflow:hidden box that actually
    // clips the board — .simulator-panel also spans the output console, so
    // fitting inside THAT still let the board slide under the console.
    const pane = await page.locator(".canvas-content").boundingBox();
    for (let i = 0; i < 8; i++) {
      await page.locator('button[title="Zoom in"]').click();
      await page.waitForTimeout(400);
      const b = await page.locator("velxio-cardputer-adv").boundingBox();
      const fits =
        b &&
        b.x >= pane.x &&
        b.y >= pane.y &&
        b.x + b.width <= pane.x + pane.width &&
        b.y + b.height <= pane.y + pane.height;
      if (!fits) {
        await page.locator('button[title="Zoom out"]').click();
        await page.waitForTimeout(400);
        break;
      }
    }
    const b = await page.locator("velxio-cardputer-adv").boundingBox();
    await shot(page, "boards/cardputer-adv-typing", {
      clip: {
        x: Math.round(Math.max(b.x, pane.x)),
        y: Math.round(Math.max(b.y, pane.y)),
        width: Math.round(
          Math.min(b.x + b.width, pane.x + pane.width) - Math.max(b.x, pane.x)
        ),
        height: Math.round(
          Math.min(b.y + b.height, pane.y + pane.height) - Math.max(b.y, pane.y)
        ),
      },
    });
  },
};

const WANT_INVENTORY = process.argv.includes("--inventory");

// ── main ─────────────────────────────────────────────────────────────────────

const requested = process.argv.slice(2).filter(a => !a.startsWith("--"));
if (process.argv.includes("--list")) {
  console.log(Object.keys(SCENES).join("\n"));
  process.exit(0);
}
const names = requested.length ? requested : Object.keys(SCENES);
for (const n of names)
  if (!SCENES[n]) {
    console.error(`unknown scene: ${n}`);
    process.exit(1);
  }

const browser = await launch();
let failed = 0;
try {
  for (const name of names) {
    console.log(`scene ${name}`);
    const page = await browser.newPage({ viewport: VIEWPORT });
    try {
      await login(page);
      await SCENES[name](page);
    } catch (e) {
      failed++;
      console.error(`  FAIL ${name}: ${e.message}`);
      try {
        await shot(page, `_debug/${name.replaceAll("/", "-")}`);
      } catch {}
    } finally {
      await page.close();
    }
  }
} finally {
  await browser.close();
}
console.log(failed ? `${failed} scene(s) failed` : "all scenes OK");
process.exit(failed ? 1 : 0);
