#!/usr/bin/env node
/**
 * Screenshot pipeline for the Velxio docs.
 *
 *   VELXIO_SHOTS_EMAIL=... VELXIO_SHOTS_PASSWORD=... node scripts/shots.mjs [scene ...]
 *
 * Captures every documented scene against a running Velxio instance
 * (default: the staging deployment) and writes them to src/assets/docs/.
 * Screenshots are regenerated by re-running this script — never edit or
 * paste them by hand, they must stay reproducible when the UI changes.
 *
 * With scene names as args, only those scenes run. `--list` prints them.
 * `--inventory` additionally dumps every visible button/label to
 * scripts/ui-inventory.json (used to maintain the selectors below).
 *
 * Env:
 *   VELXIO_BASE            target instance (default https://vstaging.moontero.com)
 *   VELXIO_SHOTS_EMAIL     login email  (required — use a test account, the
 *   VELXIO_SHOTS_PASSWORD  login pass    account name shows in the top bar)
 */
import { globSync, mkdirSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { chromium } from "playwright";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, "..", "src", "assets", "docs");
const BASE = process.env.VELXIO_BASE || "https://vstaging.moontero.com";
const EMAIL = process.env.VELXIO_SHOTS_EMAIL;
const PASS = process.env.VELXIO_SHOTS_PASSWORD;

const VIEWPORT = { width: 1280, height: 720 };

// ── infra ────────────────────────────────────────────────────────────────────

async function launch() {
  try {
    return await chromium.launch({ headless: true });
  } catch {
    const home = process.env.HOME;
    const candidates = [
      ...globSync(
        `${home}/.cache/ms-playwright/chromium_headless_shell-*/chrome-headless-shell-linux64/chrome-headless-shell`
      ),
      ...globSync(`${home}/.cache/ms-playwright/chromium-*/chrome-linux*/chrome`),
    ]
      .sort()
      .reverse();
    if (!candidates.length)
      throw new Error("no chromium — run: npx playwright install chromium");
    return chromium.launch({ headless: true, executablePath: candidates[0] });
  }
}

/** Form login is flaky on staging; the JSON endpoint is not. Log in via
 *  fetch inside the page so the session cookie lands in the browser jar. */
async function login(page) {
  if (!EMAIL || !PASS)
    throw new Error("VELXIO_SHOTS_EMAIL / VELXIO_SHOTS_PASSWORD not set");
  await page.goto(`${BASE}/`, { waitUntil: "domcontentloaded" });
  const status = await page.evaluate(
    async ({ email, password }) => {
      const r = await fetch("/api/auth/login", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ email, password }),
        credentials: "include",
      });
      return r.status;
    },
    { email: EMAIL, password: PASS }
  );
  if (status !== 200) throw new Error(`login failed: HTTP ${status}`);
  await page.reload({ waitUntil: "domcontentloaded" });
  await page.waitForTimeout(3000);
}

/** The news/announcement overlay opens over the toolbar on fresh sessions
 *  and swallows clicks. Presentational only — safe to remove. */
async function dismissOverlays(page) {
  await page.evaluate(() => {
    for (const el of document.querySelectorAll(".velxio-news-overlay")) el.remove();
  });
}

async function shot(page, relPath, opts = {}) {
  const file = join(OUT, `${relPath}.png`);
  mkdirSync(dirname(file), { recursive: true });
  await page.screenshot({ path: file, fullPage: false, ...opts });
  console.log(`  saved ${relPath}.png`);
}

/** Dump every visible interactive element so scene selectors can be
 *  maintained without spelunking the frontend source. */
async function inventory(page, name) {
  const items = await page.evaluate(() => {
    const out = [];
    const walk = (root) => {
      for (const el of root.querySelectorAll(
        "button, a[href], [role=button], input, select"
      )) {
        const r = el.getBoundingClientRect();
        if (r.width < 2 || r.height < 2) continue;
        out.push({
          tag: el.tagName.toLowerCase(),
          text: (el.textContent || "").trim().slice(0, 60),
          title: el.getAttribute("title") || undefined,
          aria: el.getAttribute("aria-label") || undefined,
          cls: (el.className?.baseVal ?? el.className ?? "")
            .toString()
            .slice(0, 80),
          at: [Math.round(r.x), Math.round(r.y), Math.round(r.width), Math.round(r.height)],
        });
      }
      for (const el of root.querySelectorAll("*"))
        if (el.shadowRoot) walk(el.shadowRoot);
    };
    walk(document);
    return out;
  });
  const file = join(HERE, `ui-inventory-${name}.json`);
  await writeFile(file, JSON.stringify(items, null, 2));
  console.log(`  inventory -> ${file} (${items.length} elements)`);
}

async function waitForSim(page, simLog, ms = 300_000) {
  const t0 = Date.now();
  while (Date.now() - t0 < ms) {
    if (simLog.some((l) => l.includes("in-browser"))) return true;
    if (simLog.some((l) => /guest crashed/i.test(l))) return false;
    await page.waitForTimeout(2000);
  }
  return false;
}

async function loadExample(page, slug) {
  await page.goto(`${BASE}/example/${slug}`, { waitUntil: "domcontentloaded" });
  await page.waitForTimeout(6000); // canvas + example hydration
  await dismissOverlays(page);
}

async function clickRun(page) {
  await page
    .locator('button[title*="Run" i], button:has-text("Run")')
    .first()
    .click();
}

// ── scenes ───────────────────────────────────────────────────────────────────
// Each scene navigates, prepares the state and captures one or more shots.
// Keep scenes independent: assume a fresh logged-in page, no leftover state.

const SCENES = {
  /** The editor as a signed-in user first sees it. */
  "getting-started/app-home": async (page) => {
    await page.goto(`${BASE}/`, { waitUntil: "domcontentloaded" });
    await page.waitForTimeout(6000);
    await dismissOverlays(page);
    await shot(page, "getting-started/app-home");
    if (WANT_INVENTORY) await inventory(page, "app-home");
  },

  /** Blink example: loaded, then running with the sim alive. */
  "getting-started/first-project": async (page) => {
    const simLog = [];
    page.on("console", (m) => {
      if (/esp32sim|guest crashed|in-browser/i.test(m.text())) simLog.push(m.text());
    });
    await loadExample(page, "esp32-blink-led");
    await shot(page, "getting-started/first-project-loaded");
    if (WANT_INVENTORY) await inventory(page, "example-editor");
    await clickRun(page);
    await waitForSim(page, simLog);
    await page.waitForTimeout(5000); // guest boot + first blinks
    await shot(page, "getting-started/first-project-running");
  },

  /** The public examples gallery. */
  "getting-started/examples-gallery": async (page) => {
    await page.goto(`${BASE}/examples`, { waitUntil: "domcontentloaded" });
    await page.waitForTimeout(4000);
    await dismissOverlays(page);
    await shot(page, "getting-started/examples-gallery");
    if (WANT_INVENTORY) await inventory(page, "examples-gallery");
  },

  /** Editor dialogs that need no running sim: component picker, datasheet
   *  (right-click), part properties, save-project, starter templates. */
  "circuit-editor/dialogs": async (page) => {
    await loadExample(page, "esp32-blink-led");

    // Component picker ("Add" in the toolbar)
    await page.locator('button[title="Add Component"]').click();
    await page.waitForTimeout(1500);
    await shot(page, "circuit-editor/component-picker");
    if (WANT_INVENTORY) await inventory(page, "component-picker");
    await page.keyboard.press("Escape");
    await page.waitForTimeout(500);

    // Part inspector (right-click a part: properties, pins and datasheet).
    // Playwright's right-click gets swallowed somewhere in the canvas stack,
    // so dispatch the contextmenu event directly — React listens at the root.
    await page.evaluate(() => {
      // The LED, not the resistor: the LED has an authored datasheet, so the
      // Datasheet tab shot shows real content instead of the empty state.
      const el = document.querySelector("wokwi-led");
      const r = el.getBoundingClientRect();
      el.dispatchEvent(
        new MouseEvent("contextmenu", {
          bubbles: true,
          cancelable: true,
          clientX: Math.min(r.x + r.width / 2, 640),
          clientY: Math.min(r.y + r.height / 2, 400),
        })
      );
    });
    await page.waitForTimeout(1500);
    await shot(page, "circuit-editor/part-inspector");
    if (WANT_INVENTORY) await inventory(page, "part-inspector");
    await page.locator('text="Datasheet"').first().click();
    await page.waitForTimeout(1000);
    await shot(page, "circuit-editor/datasheet");
    await page.keyboard.press("Escape");
    await page.waitForTimeout(500);

    // Save project dialog
    await page.locator('button[title^="Save project"]').click();
    await page.waitForTimeout(1200);
    await shot(page, "getting-started/save-project");
    await page.locator('button:has-text("Cancel")').first().click();
    await page.waitForTimeout(500);

    // Starter template picker (modal, per David's preference)
    await page.locator('button[title^="New workspace"]').click();
    await page.waitForTimeout(1200);
    await shot(page, "getting-started/starter-templates");
    if (WANT_INVENTORY) await inventory(page, "starter-templates");
    await page.keyboard.press("Escape");
  },

  /** Oscilloscope over the running blink example. */
  "instruments/oscilloscope": async (page) => {
    const simLog = [];
    page.on("console", (m) => {
      if (/esp32sim|guest crashed|in-browser/i.test(m.text())) simLog.push(m.text());
    });
    await loadExample(page, "esp32-blink-led");
    await clickRun(page);
    await waitForSim(page, simLog);
    await page.waitForTimeout(4000);
    await page.locator('button[title="Toggle Oscilloscope / Logic Analyzer"]').click();
    await page.waitForTimeout(1500);
    // Monitor the blinking pin: add a channel on GPIO2
    await page.locator('button:has-text("Add Channel")').click();
    await page.waitForTimeout(1200);
    await shot(page, "instruments/oscilloscope-add-channel");
    if (WANT_INVENTORY) await inventory(page, "oscilloscope-pinpicker");
    await page.locator('button:text-is("GPIO2")').click();
    // 100 ms/div frames the 1 s blink square wave nicely (1 ms/div is flat)
    await page.locator("select.osc-select").first().selectOption("100");
    await page.waitForTimeout(6000); // let traces accumulate
    await shot(page, "instruments/oscilloscope");
    if (WANT_INVENTORY) await inventory(page, "oscilloscope");
  },

  /** Serial monitor close-up over the running blink example. */
  "programming/serial-monitor": async (page) => {
    const simLog = [];
    page.on("console", (m) => {
      if (/esp32sim|guest crashed|in-browser/i.test(m.text())) simLog.push(m.text());
    });
    await loadExample(page, "esp32-blink-led");
    await clickRun(page);
    await waitForSim(page, simLog);
    await page.waitForTimeout(6000); // some serial output first
    await shot(page, "programming/serial-monitor", {
      clip: { x: 0, y: 520, width: 905, height: 200 },
    });
  },

  /** The AI panel in each of its three modes (right-hand column clip). */
  "ai/modes": async (page) => {
    await loadExample(page, "esp32-blink-led");
    const clip = { x: 900, y: 0, width: 380, height: 720 };
    for (const mode of ["Basic", "Agent", "Tutor"]) {
      await page.locator(`button.mode-pill:has-text("${mode}")`).click();
      await page.waitForTimeout(1200);
      await shot(page, `ai/mode-${mode.toLowerCase()}`, { clip });
    }
  },
};

const WANT_INVENTORY = process.argv.includes("--inventory");

// ── main ─────────────────────────────────────────────────────────────────────

const requested = process.argv.slice(2).filter((a) => !a.startsWith("--"));
if (process.argv.includes("--list")) {
  console.log(Object.keys(SCENES).join("\n"));
  process.exit(0);
}
const names = requested.length ? requested : Object.keys(SCENES);
for (const n of names)
  if (!SCENES[n]) {
    console.error(`unknown scene: ${n}`);
    process.exit(1);
  }

const browser = await launch();
let failed = 0;
try {
  for (const name of names) {
    console.log(`scene ${name}`);
    const page = await browser.newPage({ viewport: VIEWPORT });
    try {
      await login(page);
      await SCENES[name](page);
    } catch (e) {
      failed++;
      console.error(`  FAIL ${name}: ${e.message}`);
      try {
        await shot(page, `_debug/${name.replaceAll("/", "-")}`);
      } catch {}
    } finally {
      await page.close();
    }
  }
} finally {
  await browser.close();
}
console.log(failed ? `${failed} scene(s) failed` : "all scenes OK");
process.exit(failed ? 1 : 0);
