#!/usr/bin/env node
/**
 * Scan the English docs tree and queue any missing translations.
 *
 *   node scripts/translate-detect.mjs
 *
 * A job is queued for every (page, locale) where the locale copy is missing
 * OR out of date. "Out of date" means the English source's hash no longer
 * matches the hash recorded when that job last completed: before this,
 * rewriting an English page left its eight translations frozen forever,
 * because a completed job blocked the (page, locale) pair from ever being
 * queued again. Only brand-new pages were ever translated.
 *
 * Jobs completed before hashes existed are stamped with the current source
 * hash on first sight (a migration seal, so this change does not re-translate
 * the whole portal at once) — but a MISSING target still re-queues them, so
 * deleting a stale translation remains a valid way to force a redo.
 *
 * Pages under parts/ are excluded — they're generated by
 * gen-parts.mjs and stay in English. .mdx pages (the splash landings) are
 * excluded too: they're few and hand-translated.
 *
 * Locale list must match astro.config.mjs.
 */
import { readdirSync, existsSync, readFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { join, relative } from "node:path";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { loadQueue, saveQueue, jobKey, summarizeQueue } from "./translate/queue.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const DOCS = join(ROOT, "src", "content", "docs");

export const TARGET_LOCALES = ["es", "pt-br", "it", "fr", "zh-cn", "de", "ja", "ru"];
const EXCLUDE_DIRS = new Set(["parts", ...TARGET_LOCALES]);

function walk(dir, rel = "") {
  const out = [];
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    if (e.isDirectory()) {
      if (rel === "" && EXCLUDE_DIRS.has(e.name)) continue;
      // generated board reference stays English, like parts/
      if (join(rel, e.name) === "boards/reference") continue;
      out.push(...walk(join(dir, e.name), join(rel, e.name)));
    } else if (e.name.endsWith(".md")) {
      out.push(join(rel, e.name));
    }
  }
  return out;
}

const sourceHash = (file) =>
  createHash("sha256").update(readFileSync(file, "utf8")).digest("hex").slice(0, 16);

const pages = walk(DOCS).sort();
const queue = await loadQueue();
const byKey = new Map(queue.jobs.map(j => [jobKey(j.relPath, j.targetLocale), j]));
let added = 0;
let requeued = 0;
let sealed = 0;

for (const rel of pages) {
  const hash = sourceHash(join(DOCS, rel));
  for (const locale of TARGET_LOCALES) {
    const target = join(DOCS, locale, rel);
    const existing = byKey.get(jobKey(rel, locale));

    if (existing) {
      const missing = !existsSync(target);
      if (existing.status === "pending") {
        existing.sourceHash = hash;
        continue;
      }
      if (existing.sourceHash === undefined) {
        // Pre-hash job: seal it, but a missing target still forces a redo.
        existing.sourceHash = hash;
        sealed++;
        if (!missing) continue;
      } else if (existing.sourceHash === hash && !missing) {
        continue;
      }
      existing.status = "pending";
      existing.attempts = 0;
      existing.lastError = null;
      existing.completedAt = null;
      existing.nextAttemptAt = new Date().toISOString();
      existing.sourceHash = hash;
      requeued++;
      continue;
    }

    if (existsSync(target)) continue;
    queue.jobs.push({
      relPath: rel,
      sourceLocale: "en",
      targetLocale: locale,
      sourceFile: relative(ROOT, join(DOCS, rel)),
      targetFile: relative(ROOT, target),
      status: "pending",
      attempts: 0,
      lastError: null,
      createdAt: new Date().toISOString(),
      nextAttemptAt: new Date().toISOString(),
      completedAt: null,
      sourceHash: hash,
    });
    added++;
  }
}

await saveQueue(queue);
console.log(
  `pages: ${pages.length}, queued now: ${added}, re-queued (source changed or target missing): ${requeued}, sealed pre-hash jobs: ${sealed}`,
);
console.log(summarizeQueue(queue));
