#!/usr/bin/env node
/**
 * Scan the English docs tree and queue any missing translations.
 *
 *   node scripts/translate-detect.mjs
 *
 * A job is queued for every (page, locale) where the locale copy does not
 * exist yet. Pages under parts/ are excluded — they're generated by
 * gen-parts.mjs and stay in English. .mdx pages (the splash landings) are
 * excluded too: they're few and hand-translated.
 *
 * Locale list must match astro.config.mjs.
 */
import { readdirSync, existsSync } from "node:fs";
import { join, relative } from "node:path";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { loadQueue, saveQueue, jobKey, summarizeQueue } from "./translate/queue.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const DOCS = join(ROOT, "src", "content", "docs");

export const TARGET_LOCALES = ["es", "pt-br", "it", "fr", "zh-cn", "de", "ja", "ru"];
const EXCLUDE_DIRS = new Set(["parts", ...TARGET_LOCALES]);

function walk(dir, rel = "") {
  const out = [];
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    if (e.isDirectory()) {
      if (rel === "" && EXCLUDE_DIRS.has(e.name)) continue;
      out.push(...walk(join(dir, e.name), join(rel, e.name)));
    } else if (e.name.endsWith(".md")) {
      out.push(join(rel, e.name));
    }
  }
  return out;
}

const pages = walk(DOCS).sort();
const queue = await loadQueue();
const known = new Set(queue.jobs.map(j => jobKey(j.relPath, j.targetLocale)));
let added = 0;

for (const rel of pages) {
  for (const locale of TARGET_LOCALES) {
    const target = join(DOCS, locale, rel);
    if (existsSync(target)) continue;
    if (known.has(jobKey(rel, locale))) continue;
    queue.jobs.push({
      relPath: rel,
      sourceLocale: "en",
      targetLocale: locale,
      sourceFile: relative(ROOT, join(DOCS, rel)),
      targetFile: relative(ROOT, target),
      status: "pending",
      attempts: 0,
      lastError: null,
      createdAt: new Date().toISOString(),
      nextAttemptAt: new Date().toISOString(),
      completedAt: null,
    });
    added++;
  }
}

await saveQueue(queue);
console.log(`pages: ${pages.length}, queued now: ${added}`);
console.log(summarizeQueue(queue));
